#if !canImport(ObjectiveC)
import XCTest

extension SwiftSDL2ImageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftSDL2ImageTests = [
        ("testInit", testInit),
        ("testLoad", testLoad),
        ("testVersion", testVersion)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftSDL2ImageTests.__allTests__SwiftSDL2ImageTests)
    ]
}
#endif
