#if !canImport(ObjectiveC)
import XCTest

extension SDL2ImageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDL2ImageTests = [
        ("testInit", testInit),
        ("testLoad", testLoad),
        ("testVersion", testVersion)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDL2ImageTests.__allTests__SDL2ImageTests)
    ]
}
#endif
