#if !canImport(ObjectiveC)
import XCTest

extension SwiftSDLImageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftSDLImageTests = [
        ("testInit", testInit),
        ("testLoad", testLoad),
        ("testVersion", testVersion)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftSDLImageTests.__allTests__SwiftSDLImageTests)
    ]
}
#endif
